apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  # nodeName: ip-10-66-148-166.ap-southeast-1.compute.internal
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
